[main]
font = JetBrainsMono Nerd Font Mono:size=18:weight=bold
width = 30
lines = 15
prompt = >

[colors]
# If you have 6-digit RGB values, append 'ff' for full opacity.
background = 000000B3
text = ccccccB3
match = 7fc8ffff
selection = 00000000
selection-text = 7fc8ffff
border = 7fc8ffff
