[main]
font = JetBrainsMono Nerd Font Mono 20
width = 50
lines = 15
prompt = >
border-width = 1

[colors]
# If you have 6-digit RGB values, append 'ff' for full opacity.
background = 000000cc
text = ccccccff
match = 7fc8ffff
selection = 000000cc
selection-text = 7fc8ffff
border = 333333ff
