[main]
font = JetBrainsMono Nerd Font Mono:size=18
width = 50
lines = 15
prompt = >

[colors]
# If you have 6-digit RGB values, append 'ff' for full opacity.
background = 000000B3
text = ccccccff
match = 7fc8ffff:weight=bold
selection = 00000000
selection-text = 7fc8ffff:weight=bold
border = 7fc8ffff
